### PR TITLE
add -j|--jokes option, where it shows a random joke in jokes.txt file

### PR DESCRIPTION
**Pull request by cer-nagas**
Instead of writing the boring "Type password to unlock", I think it would be nice if we can show some random jokes while the monitor is locked with -j option.
The one-line-jokes can be stored in jokes.txt file, with one joke is (obviously) one line.

### CODE REVIEW

**Comment by meskarune** [comment]
I love this! Would you mind updating to the latest revision and maybe changing -j/--joke to -r/--random so people can set a list of random messages. They could be jokes, quotes or whatever else they want in random.txt. <3

**Comment by cer-nagas** [comment]
Sure, my lady. I have made the modifications you mentioned. It would be better that way. :)

But I'm thinking about 2 changes that can make it even better:
1. When a joke/quote is long, it should be split into 2 lines. Is there an (easy and beautiful) way in doing so?
2. The $RANDOM variable is now set as global, which may affect the -t (or other options) later on. I thought about instead of pure "RANDOM=true", could "export RANDOM=true" create a temporary variable inside the script and doesn't affect next time it's run? Or is there any alternative solution for this? I haven't tested it yet, since something is not right with my system and I'm busy with it. This can be marked as an issue, but I think it's not worth it so we can just talk about it here. :D

**Comment by AladW** [comment]
You're having some git indicators left-over from rebasing. Also, why hardcode the name to random.txt, rather than specify it on the command line?

Personally I think there's little benefit in implementing this in the script itself. For example, you can already do:
```
$ ./lock -t $(shuf -n1 random.txt)
```

**Comment by AladW** [comment]
If you have a patch to split the lins for -t, feel free to create a pull request for that. Closing this one as wontfix for reasons outlined above.

**Pull request closed without merging**
