### PR TITLE
fix imagemagick bug on branch Dualmonitors 

### PR DESCRIPTION
**Pull request by Drayer34**
Hi,
I notice that i3lock-fancy-dualmonitors-git was not compatible with the new version of ImageMagick, so i made some change to make it work.

I also add the flag to display the number of failed login.

### CODE REVIEW

**Comment by sim590** [comment]
I feel like this was merely an imagemagick upstream (or possibly archlinux package) mistake. I was having issues up until the version `imagemagick-7.0.7.34-1` on archlinux. It now works as it did without this change. @Drayer34: I guess you can abandon this PR.

**Comment by sim590** [comment]
@Drayer34: Can you explicit the actual error message you get and the version for imagemagick. With `ImageMagick 7.0.7-34 Q16 x86_64 2018-05-20`, I get a crash one time out of 2 or 3. It's non predictable AFAIK. Here's the error message I get:

```
free(): invalid size
/usr/bin/i3lock-fancy : ligne 78 : 20893 Abandon                 (core dumped)convert "$IMAGE" "${HUE[@]}" "${EFFECT[@]}" "${LOCK[@]}" "$IMAGE"
```

**Comment by sim590** [comment]
What ever the actual issue is, I can confirm that your changes seem to fix the crashes.

**Comment by Drayer34** [comment]
@sim590 : That was the same error as in this issue : https://github.com/meskarune/i3lock-fancy/issues/115.

I don't know if it's a temporary issue from imagemagick, but i wanted to go around this bug.

A good idea may be to see what change in imagemagick to cause this error message and see if it's a design choice in the new version or a bug.

**Comment by sim590** [comment]
> @sim590 : That was the same error as in this issue : #115.

As stated in #115, the issue is gone after `7.0.7-34`. However, as said above, I get non systematic crashes with another error message, but again, your workaround fixes that too.

> A good idea may be to see what change in imagemagick to cause this error message and see if it's a design choice in the new version or a bug.

As reported in #115:

> The internal ImageMagick SVG renderer is not fully compliant with the specification. Instead we recommend you build ImageMagick with an alternative renderer, libRSVG, or inkscape.

Therefore, I think that the fix is a good one, especially if we don't really need those instructions. It seems to me, after some quick visual testing, that those lines are not required. The original author could tell us otherwise it's the case.

**Comment by Drayer34** [comment]
> Can you remove this commit?

Yes of course

**Comment by PandorasFox** [comment]
`-f` just shoes the number of failed login attempts. If users want it then it should go into additional params, and definitely shouldn't be hard-coded.

**Comment by AladW** [comment]
Is this still relevant?

**Comment by meskarune** [comment]
I think using the latest version of image magick fixes this.

**Comment by AladW** [comment]
Great, thanks.

**Pull request closed without merging**
